### ISSUE TITLE
基于jansenyang的源库，解决了22日新增的签名问题吗？

### ISSUE THREAD

**Issue by PrettinYu** [soundofautumn/dingdong-helper-console#1]

**Comment by soundofautumn** [comment]
还没有，我电脑上突然就抓不到小程序的包了，也没法测试，等别人研究出来我再改吧，现在此程序应该是不可用的状态

**Comment by PrettinYu** [comment]
> 

我在sunquan.api.ddxp抓到，不确定正确性，config测试是没问题的
更新为你的版本后昨晚测试，没有出现“当前人多拥挤，请稍后尝试刷新页面”的提示，反馈是无可选配送时间，和老版本能抢到时提示一致。
今早试抢，没成功，依然反馈风控提示，甚至小程序会突然注销登录，重登更新config

**Comment by soundofautumn** [comment]
等原仓库更新了或者有别的解决方案了我再同步一下，小程序逆向什么的不是很懂
